export const knowledgeCategories = [
  'Standards & Regulations',
  'Industry Centers',
  'Security Advisories',
  'OICC Guidance',
  'Research & Evidence',
  'Regulatory Updates'
]

export const knowledgeResources = [
  {
    slug:'papercut-ng-mf-urgent-security-advisory',
    title:'PaperCut NG/MF urgent security advisory',
    source:'PaperCut Software',
    authority:'Security / Technical Source',
    type:'Security Advisory',
    category:'Security Advisories',
    industry:'All Industries',
    domains:['Secure Configuration','Visibility & Evidence','Service & Supply Chain'],
    date:'August 27, 2026',
    updated:'September 1, 2026',
    reviewed:'September 3, 2026',
    status:'Updated',
    url:'https://www.papercut.com/kb/Main/security-bulletin-27-aug-2026-urgent-security-advisory/',
    summary:'PaperCut reported active exploitation affecting PaperCut NG and MF. Its September 1 Emergency Patch Release 3 superseded earlier emergency patches, and PaperCut recommended immediate action for internet-facing Application Servers.',
    relevance:'Demonstrates that output security includes print-management servers, management interfaces, logs, databases, identity connections, and remote-access tools—not only the physical printer.'
  },
  {
    slug:'post-quantum-security-mainstream-print',
    title:'Post-quantum security moves into mainstream print',
    source:'Quocirca',
    authority:'Research / Evidence',
    type:'Substantive Analysis',
    category:'Research & Evidence',
    industry:'All Industries',
    domains:['Lifecycle Assurance'],
    date:'July 13, 2026',
    reviewed:'August 28, 2026',
    url:'https://quocirca.com/content/post-quantum-security-moves-into-mainstream-print/',
    summary:'Analysis of post-quantum readiness in print, including secure boot, firmware signing, device identity, certificates, encrypted communications, and cryptographic agility across long device lifecycles.',
    relevance:'Supports treating post-quantum readiness as a lifecycle capability: output endpoints must preserve identity, communications security, firmware integrity, and trust as cryptographic standards change.'
  },
  {
    slug:'nist-cybersecurity-framework-2',
    title:'NIST Cybersecurity Framework 2.0',
    source:'National Institute of Standards and Technology',
    authority:'Primary Authority',
    type:'Framework',
    category:'Standards & Regulations',
    industry:'All Industries',
    jurisdiction:'United States',
    domains:['Governance & Ownership'],
    date:'February 26, 2024',
    reviewed:'July 18, 2026',
    status:'Final',
    url:'https://www.nist.gov/cyberframework',
    summary:'A risk-based framework organized around Govern, Identify, Protect, Detect, Respond, and Recover.',
    relevance:'Provides a governing structure for bringing output systems into an organization-wide cybersecurity risk program.'
  },
  {
    slug:'nist-sp-800-53-rev-5',
    title:'NIST SP 800-53 Rev. 5',
    source:'NIST Computer Security Resource Center',
    authority:'Primary Authority',
    type:'Security Controls',
    category:'Standards & Regulations',
    industry:'Government & Defense',
    jurisdiction:'United States',
    domains:['Secure Configuration'],
    date:'December 10, 2020',
    reviewed:'July 18, 2026',
    status:'Final',
    url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',
    summary:'A flexible catalog of security and privacy controls for information systems and organizations.',
    relevance:'Supports control selection for access, configuration, audit, communications, maintenance, media, supply chain, and system integrity in output environments.'
  },
  {
    slug:'nist-sp-800-53a-rev-5',
    title:'NIST SP 800-53A Rev. 5',
    source:'NIST Computer Security Resource Center',
    authority:'Primary Authority',
    type:'Assessment Guidance',
    category:'Standards & Regulations',
    industry:'Government & Defense',
    jurisdiction:'United States',
    domains:['Visibility & Evidence'],
    date:'January 25, 2022',
    reviewed:'July 18, 2026',
    status:'Final',
    url:'https://csrc.nist.gov/pubs/sp/800/53/a/r5/final',
    summary:'Assessment procedures and methodology for evaluating security and privacy controls.',
    relevance:'Helps turn an output-security control statement into evidence that can be examined, tested, and documented.'
  },
  {
    slug:'nist-sp-800-171-rev-3',
    title:'NIST SP 800-171 Rev. 3',
    source:'NIST Computer Security Resource Center',
    authority:'Primary Authority',
    type:'Security Requirements',
    category:'Standards & Regulations',
    industry:'Government & Defense',
    jurisdiction:'United States',
    domains:['Data Protection'],
    date:'May 14, 2024',
    reviewed:'July 18, 2026',
    status:'Final',
    url:'https://csrc.nist.gov/pubs/sp/800/171/r3/final',
    summary:'Recommended security requirements for protecting the confidentiality of CUI in nonfederal systems and organizations.',
    relevance:'Relevant when output devices, queues, workflows, storage, service processes, or physical documents handle controlled information.'
  },
  {
    slug:'zero-trust-maturity-model-v2',
    title:'Zero Trust Maturity Model Version 2.0',
    source:'Cybersecurity and Infrastructure Security Agency',
    authority:'Authoritative Guidance',
    type:'Implementation Guidance',
    category:'Standards & Regulations',
    industry:'Government & Defense',
    jurisdiction:'United States',
    domains:['Identity & Access'],
    date:'April 11, 2023',
    reviewed:'July 18, 2026',
    url:'https://www.cisa.gov/resources-tools/resources/zero-trust-maturity-model',
    summary:'A maturity model for advancing identity, device, network, application, workload, and data protections.',
    relevance:'Provides a useful lens for questioning implicit trust in output endpoints, administrators, users, service paths, and device data.'
  },
  {
    slug:'zero-trust-operational-technology',
    title:'Adapting Zero Trust Principles to Operational Technology',
    source:'CISA and Joint Authoring Organizations',
    authority:'Authoritative Guidance',
    type:'Implementation Guidance',
    category:'Research & Evidence',
    industry:'Manufacturing',
    jurisdiction:'United States',
    domains:['Recovery & Continuity'],
    date:'April 29, 2026',
    reviewed:'July 18, 2026',
    url:'https://www.cisa.gov/sites/default/files/2026-04/joint-guide-adapting-zero-trust-principles-to-operational-technology_508c.pdf',
    summary:'Joint guidance for applying Zero Trust principles while respecting safety, availability, and operational constraints.',
    relevance:'Useful where output systems support production, segmented environments, critical processes, or locations where availability shapes security decisions.'
  }
]
